### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by AlbertoDePena** [ThisFunctionalTom/Html2Feliz#2]

**Comment by ThisFunctionalTom** [comment]
I am not actively working on it but if you have an idea how to make it better we can look together into it if you'd like.

**Comment by AlbertoDePena** [comment]
I would love that. Been looking for html to Feliz just like the existing fable syntax. I was thinking just providing an empty text box to copy html snippets and auto generate the Feliz equivalent.

**Comment by ThisFunctionalTom** [comment]
Cool. Would you like to make a PR, should I do it or we can try pair-programming if you'd want to?

**Comment by ThisFunctionalTom** [comment]
I added fantomas and reformated the code a little bit. I hope now it is simpler to follow and change.

**Comment by AlbertoDePena** [comment]
@ThisFunctionalTom, I just need two panels, one for the input and one for the output. Just so I can copy random HTML and have it convert it to Feliz equivalent. Would you mind if I borrow some of your code?

**Comment by ThisFunctionalTom** [comment]
> @ThisFunctionalTom, I just need two panels, one for the input and one for the output. Just so I can copy random HTML and have it convert it to Feliz equivalent. Would you mind if I borrow some of your code?

No problem. Copy everything you need.
You can already paste in any HTML into the left input box and you get the converted code in the right text box. 
Is till don't understand what would you like to have differently but you can do whatever you want?

**Comment by AlbertoDePena** [comment]
My bad, I just realized that I already can accomplish what I needed from your current implementation. Thank you so much for this =)

**Comment by ThisFunctionalTom** [comment]
I guess it is OK if I close this.
